apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fixbot-ingress
  namespace: fixbot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '600'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fixbot.hackathon.sev-2.com
      secretName: fixbot-tls
  rules:
    - host: fixbot.hackathon.sev-2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fixbot-service
                port:
                  number: 80
