apiVersion: v1
kind: Service
metadata:
  name: fixbot-backstage
  namespace: fixbot
  labels:
    app: fixbot-backstage
spec:
  type: ClusterIP
  selector:
    app: fixbot-backstage
  ports:
    - name: http
      port: 80
      targetPort: 7007
      protocol: TCP
